// Curated brand -> category mapping, for a future brand picker/autocomplete
// on the Brand field. Category values match CATEGORIES in grouping.js.
// Deliberately category-only, never subcategory — linking brands down to
// subcategory would create far more (and far more fragile) associations
// than this is worth. A brand that genuinely spans categories (e.g. a
// fashion house that does both clothing and beauty) lists more than one.
//
// Whatever picker gets built on top of this must still allow free-text
// manual entry of a brand that isn't in this list — no curated list this
// size will ever be complete.
export const BRAND_CATEGORIES = {
  'Acne Studios': ['clothing'],
  Adidas: ['shoes', 'clothing'],
  Aigle: ['shoes', 'clothing'],
  'Alexander McQueen': ['clothing', 'accessories'],
  'Alice + Olivia': ['clothing'],
  'American Eagle': ['clothing'],
  'American Vintage': ['clothing'],
  'Ami Paris': ['clothing'],
  Anteprima: ['bags'],
  Aquascutum: ['clothing'],
  "Arc'teryx": ['clothing', 'outdoors'],
  Armani: ['beauty'],
  Ashworth: ['clothing'],
  Asics: ['shoes'],
  'Atsuro Tayama': ['clothing'],
  Balenciaga: ['luxury'],
  Bally: ['shoes', 'bags'],
  'Banana Republic': ['clothing'],
  Barbour: ['clothing'],
  'Bath & Body Works': ['beauty'],
  'Bora Aksu': ['clothing'],
  Boss: ['clothing'],
  'Bottega Veneta': ['luxury', 'beauty'],
  Breitling: ['electronics'],
  Brioni: ['clothing'],
  'Brooks Brothers': ['clothing'],
  'Brunello Cucinelli': ['luxury'],
  Burberry: ['clothing'],
  'C.P. Company': ['clothing'],
  Callaway: ['outdoors'],
  'Calvin Klein': ['clothing'],
  Camper: ['shoes'],
  CASETiFY: ['electronics'],
  Casio: ['electronics'],
  'Cath Kidston': ['bags', 'home'],
  Celine: ['luxury'],
  Champion: ['clothing'],
  Chanel: ['luxury', 'beauty'],
  Chevignon: ['clothing'],
  Chloé: ['luxury'],
  'Chow Sang Sang': ['accessories'],
  'Chow Tai Fook': ['accessories'],
  'Christian Louboutin': ['shoes'],
  Citizen: ['electronics'],
  'City Chain': ['electronics'],
  Clarks: ['shoes'],
  'Club Monaco': ['clothing'],
  Coach: ['bags'],
  'Cole Haan': ['shoes'],
  Coleman: ['outdoors'],
  'Columbia Sportswear': ['clothing'],
  Comvita: ['other'],
  Converse: ['shoes'],
  Crocs: ['shoes'],
  DAKS: ['clothing'],
  DeLonghi: ['home'],
  Descente: ['clothing'],
  Diesel: ['clothing'],
  Dior: ['luxury', 'beauty'],
  'Dolce & Gabbana': ['luxury', 'beauty'],
  'Dr. Kong': ['shoes', 'kids'],
  Dsquared2: ['clothing'],
  Dunhill: ['bags', 'clothing'],
  Ecco: ['shoes'],
  Etro: ['clothing'],
  Evisu: ['clothing'],
  Fendi: ['luxury'],
  Ferragamo: ['luxury', 'beauty'],
  Fila: ['shoes', 'clothing'],
  'Fred Perry': ['clothing'],
  Furla: ['bags'],
  G2000: ['clothing'],
  Gap: ['clothing'],
  Geox: ['shoes'],
  Givenchy: ['clothing'],
  Gucci: ['luxury', 'beauty'],
  Hamilton: ['electronics'],
  'Helly Hansen': ['clothing', 'outdoors'],
  Hermès: ['luxury'],
  Hoka: ['shoes'],
  initial: ['clothing'],
  'J.Lindeberg': ['clothing'],
  'Jil Sander': ['clothing'],
  'Jimmy Choo': ['shoes'],
  'K-Swiss': ['shoes'],
  'Kate Spade New York': ['bags'],
  Kenzo: ['clothing'],
  Kipling: ['bags'],
  'Kolon Sport': ['clothing'],
  Lacoste: ['clothing'],
  'Le Creuset': ['home'],
  Lego: ['kids'],
  "Levi's": ['clothing'],
  Loewe: ['luxury'],
  Longchamp: ['bags'],
  Longines: ['electronics'],
  'Loro Piana': ['luxury'],
  'Louis Vuitton': ['luxury'],
  'Lukfook Jewellery': ['accessories'],
  Lululemon: ['clothing'],
  MaBelle: ['accessories'],
  Mackintosh: ['clothing'],
  'Maison Margiela': ['clothing'],
  Maje: ['clothing'],
  Mammut: ['clothing', 'outdoors'],
  'Manolo Blahnik': ['shoes'],
  'Marc Jacobs': ['luxury'],
  'Margaret Howell': ['clothing'],
  Marimekko: ['home', 'clothing'],
  'Marithé François Girbaud': ['clothing'],
  Marni: ['clothing'],
  Maryling: ['clothing'],
  'Matin Kim': ['clothing'],
  'MAX&Co.': ['clothing'],
  MaxMara: ['clothing'],
  'Michael Kors': ['bags', 'accessories'],
  'Miss Sixty': ['clothing'],
  'Miu Miu': ['luxury'],
  MLB: ['accessories'],
  'Molton Brown': ['beauty'],
  Moncler: ['clothing'],
  Montblanc: ['accessories', 'bags'],
  moodytiger: ['kids'],
  'National Geographic': ['clothing'],
  'New Balance': ['shoes'],
  Nike: ['shoes', 'clothing'],
  Oakley: ['accessories'],
  'Off-White': ['clothing', 'shoes'],
  Palladium: ['shoes'],
  Pandora: ['accessories'],
  'Paul Smith': ['clothing'],
  'Polo Ralph Lauren': ['clothing'],
  Prada: ['luxury'],
  Puma: ['shoes', 'clothing'],
  'Ray-Ban': ['accessories'],
  Repetto: ['shoes'],
  Replay: ['clothing'],
  Rockport: ['shoes'],
  'Roger Vivier': ['shoes'],
  'Royal Copenhagen': ['home'],
  'Rue Madame': ['clothing'],
  'Saint Laurent': ['luxury', 'beauty'],
  Salomon: ['shoes'],
  'Sam Edelman': ['shoes'],
  Samsonite: ['bags'],
  'Sandro Paris': ['clothing'],
  Seiko: ['electronics'],
  'Shanghai Tang': ['clothing'],
  Skechers: ['shoes'],
  'Stella McCartney': ['clothing'],
  'Stone Island': ['clothing'],
  Swarovski: ['accessories'],
  Swatch: ['electronics'],
  'Tag Heuer': ['electronics'],
  TaylorMade: ['outdoors'],
  'The Body Shop': ['beauty'],
  'The North Face': ['clothing', 'outdoors'],
  Theory: ['clothing'],
  Thermos: ['home'],
  'Thom Browne': ['clothing'],
  Timberland: ['shoes'],
  Tissot: ['electronics'],
  "Tod's": ['shoes'],
  'Tommy Hilfiger': ['clothing'],
  'Tory Burch': ['bags', 'accessories', 'clothing'],
  TSL: ['accessories'],
  Tumi: ['bags'],
  Ugg: ['shoes'],
  'Under Armour': ['clothing'],
  UNIQLO: ['clothing'],
  Valentino: ['luxury', 'beauty'],
  Vans: ['shoes'],
  Versace: ['luxury', 'beauty'],
  Victorinox: ['bags', 'outdoors', 'electronics'],
  Vilebrequin: ['clothing'],
  VIVAIA: ['shoes'],
  'Vivienne Westwood': ['clothing'],
  Wedgwood: ['home'],
  Woolrich: ['clothing'],
  'Y-3': ['shoes', 'clothing'],
  Zegna: ['clothing'],
  'Zero Halliburton': ['bags'],
  Zwilling: ['home'],

  // Beauty
  Aesop: ['beauty'],
  Anessa: ['beauty'],
  Albion: ['beauty'],
  Aveda: ['beauty'],
  'Benefit Cosmetics': ['beauty'],
  Biotherm: ['beauty'],
  'Bobbi Brown': ['beauty'],
  Byredo: ['beauty'],
  Chantecaille: ['beauty'],
  'Charlotte Tilbury': ['beauty'],
  Clarins: ['beauty'],
  'Clé de Peau Beauté': ['beauty'],
  Clinique: ['beauty'],
  Creed: ['beauty'],
  Decorté: ['beauty'],
  Dermalogica: ['beauty'],
  Diptyque: ['beauty'],
  'Dr. Barbara Sturm': ['beauty'],
  'Erno Laszlo': ['beauty'],
  'Estée Lauder': ['beauty'],
  Fancl: ['beauty'],
  'Fenty Beauty': ['beauty'],
  Guerlain: ['beauty'],
  'Jo Malone London': ['beauty'],
  Jurlique: ['beauty'],
  Kérastase: ['beauty'],
  "Kiehl's": ['beauty'],
  'Kilian Paris': ['beauty'],
  Kosé: ['beauty'],
  "L'Occitane en Provence": ['beauty'],
  'La Mer': ['beauty'],
  'La Prairie': ['beauty'],
  Lancôme: ['beauty'],
  Laneige: ['beauty'],
  'Le Labo': ['beauty'],
  Biore: ['beauty'],
  CeraVe: ['beauty'],
  Cetaphil: ['beauty'],
  Curél: ['beauty'],
  'Hada Labo': ['beauty'],
  'La Roche-Posay': ['beauty'],
  Maybelline: ['beauty'],
  Media: ['beauty'],
  Mediheal: ['beauty'],
  Minon: ['beauty'],
  Neutrogena: ['beauty'],
  Olay: ['beauty'],
  Orbis: ['beauty'],
  Physiogel: ['beauty'],
  Senka: ['beauty'],
  Sofina: ['beauty'],
  NARS: ['beauty'],
  MAC: ['beauty'],

  // Kids
  balabala: ['kids'],
  Bonpoint: ['kids'],
  Chicco: ['kids'],
  'Petit Bateau': ['kids'],
  'Toys"R"Us': ['kids'],
  'My Little Korner': ['kids'],
  'Petit Bazaar': ['kids'],
  Taranis: ['kids'],
}

export const KNOWN_BRANDS = Object.keys(BRAND_CATEGORIES).sort((a, b) => a.localeCompare(b))
