// Curated list of brand names carried over from the retired logo-matching
// feature (see git history for src/utils/logoMatch.js) — kept as plain data
// since it's still useful as a known-brands list (e.g. a future picker/
// autocomplete on the Brand field), independent of any logo image.
export const KNOWN_BRANDS = [
  'Acne Studios',
  'Adidas',
  'Aigle',
  'Alexander McQueen',
  'Alice + Olivia',
  'American Eagle',
  'American Vintage',
  'Ami Paris',
  'Anteprima',
  'Aquascutum',
  "Arc'teryx",
  'Armani',
  'Ashworth',
  'Asics',
  'Atsuro Tayama',
  'Balenciaga',
  'Bally',
  'Banana Republic',
  'Barbour',
  'Bath & Body Works',
  'Bora Aksu',
  'Boss',
  'Bottega Veneta',
  'Breitling',
  'Brioni',
  'Brooks Brothers',
  'Brunello Cucinelli',
  'Burberry',
  'C.P. Company',
  'Callaway',
  'Calvin Klein',
  'Camper',
  'CASETiFY',
  'Casio',
  'Cath Kidston',
  'Celine',
  'Champion',
  'Chevignon',
  'Chloé',
  'Chow Sang Sang',
  'Chow Tai Fook',
  'Christian Louboutin',
  'Citizen',
  'City Chain',
  'Clarks',
  'Club Monaco',
  'Coach',
  'Cole Haan',
  'Coleman',
  'Columbia Sportswear',
  'Comvita',
  'Converse',
  'Crocs',
  'DAKS',
  'DeLonghi',
  'Descente',
  'Diesel',
  'Dior',
  'Dolce & Gabbana',
  'Dr. Kong',
  'Dsquared2',
  'Dunhill',
  'Ecco',
  'Etro',
  'Evisu',
  'Fendi',
  'Ferragamo',
  'Fila',
  'Fred Perry',
  'Furla',
  'G2000',
  'Gap',
  'Geox',
  'Givenchy',
  'Gucci',
  'Hamilton',
  'Helly Hansen',
  'Hoka',
  'initial',
  'J.Lindeberg',
  'Jil Sander',
  'Jimmy Choo',
  'K-Swiss',
  'Kate Spade New York',
  'Kenzo',
  'Kipling',
  'Kolon Sport',
  'Lacoste',
  'Le Creuset',
  'Lego',
  "Levi's",
  'Loewe',
  'Longchamp',
  'Longines',
  'Loro Piana',
  'Lukfook Jewellery',
  'Lululemon',
  'MaBelle',
  'Mackintosh',
  'Maison Margiela',
  'Maje',
  'Mammut',
  'Manolo Blahnik',
  'Marc Jacobs',
  'Margaret Howell',
  'Marimekko',
  'Marithé François Girbaud',
  'Marni',
  'Maryling',
  'Matin Kim',
  'MAX&Co.',
  'MaxMara',
  'Michael Kors',
  'Miss Sixty',
  'Miu Miu',
  'MLB',
  'Molton Brown',
  'Moncler',
  'Montblanc',
  'moodytiger',
  'National Geographic',
  'New Balance',
  'Nike',
  'Oakley',
  'Off-White',
  'Palladium',
  'Pandora',
  'Paul Smith',
  'Polo Ralph Lauren',
  'Prada',
  'Puma',
  'Ray-Ban',
  'Repetto',
  'Replay',
  'Rockport',
  'Roger Vivier',
  'Royal Copenhagen',
  'Rue Madame',
  'Saint Laurent',
  'Salomon',
  'Sam Edelman',
  'Samsonite',
  'Sandro Paris',
  'Seiko',
  'Shanghai Tang',
  'Skechers',
  'Stella McCartney',
  'Stone Island',
  'Swarovski',
  'Swatch',
  'Tag Heuer',
  'TaylorMade',
  'The Body Shop',
  'The North Face',
  'Theory',
  'Thermos',
  'Thom Browne',
  'Timberland',
  'Tissot',
  "Tod's",
  'Tommy Hilfiger',
  'Tory Burch',
  'TSL',
  'Tumi',
  'Ugg',
  'Under Armour',
  'UNIQLO',
  'Valentino',
  'Vans',
  'Versace',
  'Victorinox',
  'Vilebrequin',
  'VIVAIA',
  'Vivienne Westwood',
  'Wedgwood',
  'Woolrich',
  'Y-3',
  'Zegna',
  'Zero Halliburton',
  'Zwilling',
]
